spring.application.name=email-writer-sb
server.port=${PORT:8080}




gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent
gemini.api.key=${GEMINI_API_KEY}

claude.api.url=https://api.anthropic.com/v1/messages
claude.api.key=${CLAUDE_API_KEY:}



